source 'https://rubygems.org'

# servicio
gem 'activerecord', '4.2.7.1'
gem 'sqlite3', '1.3.10'
gem 'sinatra', '1.4.6'

#cliente
gem 'json'
gem 'typhoeus'

# prubas
gem 'rspec', '3.2.0'
gem 'rack-test'