require 'rubygems'
require 'active_record'
require 'yaml'
require 'logger'

desc "Cargar el ambiente"
task :environment do
    env = ENV["SINATRA_ENV"] || "development"
    databases = YAML.load_file("config/database.yml")
    ActiveRecord::Base.establish_connection(databases[env])
end

namespace :db do
    desc "Migrar la base de datos"
    task(:migrate => :environment) do
        ActiveRecord::Base.logger = Logger.new(STDOUT)
        ActiveRecord::Migration.verbose = true
        ActiveRecord::Migrator.migrate("db/migrate")
    end

    desc "Eliminar la base de datos"
    task(:drop => :environment) do
        ActiveRecord::Base.logger = Logger.new(STDOUT)
        ActiveRecord::Migration.verbose = true
        ActiveRecord::Migrator.migrate("db/drop")
    end
end