package Calculator;

/**
* Calculator/SumaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, April 25, 2018 11:49:25 AM CDT
*/

public final class SumaHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculator.Suma value = null;

  public SumaHolder ()
  {
  }

  public SumaHolder (Calculator.Suma initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculator.SumaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculator.SumaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculator.SumaHelper.type ();
  }

}
