package Calculator;


/**
* Calculator/SumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, April 25, 2018 11:49:25 AM CDT
*/

public interface SumaOperations 
{
  int add (int a, int b);
  void shutdown ();
} // interface SumaOperations
