package Calculator;


/**
* Calculator/Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, April 25, 2018 12:45:05 PM CDT
*/

public interface Operations extends OperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operations
