package Calculator;


/**
* Calculator/Suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, April 25, 2018 11:49:25 AM CDT
*/

public interface Suma extends SumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Suma
