package Calculator;


/**
* Calculator/OperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, April 25, 2018 12:45:05 PM CDT
*/

public interface OperationsOperations 
{
  int suma (int a, int b);
  int resta (int a, int b);
  int multiplicacion (int a, int b);
  float division (int a, int b);
  double potencia (int a, int b);
  double raizc (int a);
  void desligar ();
} // interface OperationsOperations
