package Calculator;


/**
* Calculator/OperationsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, April 25, 2018 12:45:04 PM CDT
*/

public abstract class OperationsPOA extends org.omg.PortableServer.Servant
 implements Calculator.OperationsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("suma", new java.lang.Integer (0));
    _methods.put ("resta", new java.lang.Integer (1));
    _methods.put ("multiplicacion", new java.lang.Integer (2));
    _methods.put ("division", new java.lang.Integer (3));
    _methods.put ("potencia", new java.lang.Integer (4));
    _methods.put ("raizc", new java.lang.Integer (5));
    _methods.put ("desligar", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculator/Operations/suma
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.suma (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Calculator/Operations/resta
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.resta (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Calculator/Operations/multiplicacion
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.multiplicacion (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // Calculator/Operations/division
       {
         int a = in.read_long ();
         int b = in.read_long ();
         float $result = (float)0;
         $result = this.division (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // Calculator/Operations/potencia
       {
         int a = in.read_long ();
         int b = in.read_long ();
         double $result = (double)0;
         $result = this.potencia (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // Calculator/Operations/raizc
       {
         int a = in.read_long ();
         double $result = (double)0;
         $result = this.raizc (a);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 6:  // Calculator/Operations/desligar
       {
         this.desligar ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculator/Operations:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Operations _this() 
  {
    return OperationsHelper.narrow(
    super._this_object());
  }

  public Operations _this(org.omg.CORBA.ORB orb) 
  {
    return OperationsHelper.narrow(
    super._this_object(orb));
  }


} // class OperationsPOA
