-- MySQL Script generated by MySQL Workbench
-- Mon Jun 11 14:19:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cumpleanos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cumpleanos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cumpleanos` DEFAULT CHARACTER SET utf8 ;
USE `cumpleanos` ;

-- -----------------------------------------------------
-- Table `cumpleanos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cumpleanos`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(55) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cumpleanos`.`felicitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cumpleanos`.`felicitaciones` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_usuario_destino` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT NOW(),
  `visualizado` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_felicitacion_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_felicitacion_usuario1_idx` (`id_usuario_destino` ASC),
  PRIMARY KEY (`id_notificacion`),
  CONSTRAINT `fk_felicitacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cumpleanos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_felicitacion_usuario1`
    FOREIGN KEY (`id_usuario_destino`)
    REFERENCES `cumpleanos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `usuario` VALUES (1,'Caio Amaral','caioaba','123','1994-08-11 00:00:00'),(2,'Rafael Silas','rafa','123','1994-06-11 00:00:00'),(3,'Michael Munson','michael','123','1993-05-11 00:00:00'),(4,'Carlos Magno','carlos','123','1998-06-11 00:00:00');